// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using card_dispute_portal.DataAccess;

#nullable disable

namespace card_dispute_portal.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251002095603_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("card_dispute_portal.Models.CardTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("CardLast4")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisputeReason")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DisputeStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Merchant")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CardTransactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 120.50m,
                            CardLast4 = "1234",
                            CreatedDate = new DateTime(2025, 10, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2025, 10, 2),
                            Description = "Groceries",
                            DisputeStatus = 0,
                            Merchant = "Store A"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 45.00m,
                            CardLast4 = "5678",
                            CreatedDate = new DateTime(2025, 10, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2025, 10, 2),
                            Description = "Fuel",
                            DisputeStatus = 0,
                            Merchant = "Store B"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 75.25m,
                            CardLast4 = "9876",
                            CreatedDate = new DateTime(2025, 10, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2025, 10, 2),
                            Description = "Electronics",
                            DisputeStatus = 0,
                            Merchant = "Store C"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
